Backport assert_never change to include repr of value
This helps to debug what bad data you have.

Via https://github.com/python/cpython/commit/93d280141c369fd1906569ff605148b6e22f6a43#diff-ddb987fca5f5df0c9a2f5521ed687919d70bb3d64eaeb8021f98833a2a716887

```pycon
$ PYTHONPATH=src python3.10
>>> import typing_extensions
>>> typing_extensions.__file__
'typing_extensions/src/typing_extensions.py'
>>> typing_extensions.assert_never("boo!")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "typing_extensions/src/typing_extensions.py", line 2387, in assert_never
    raise AssertionError(f"Expected code to be unreachable, but got: {value}")
AssertionError: Expected code to be unreachable, but got: 'boo!'
```